name: Main Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run lint
        run: pnpm lint

  compile:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run build
        run: pnpm build
